### ISSUE TITLE
Slovak translation - completion

### ISSUE THREAD

**Issue by PSYCHEER** [supercrafter100/Nameless-Suggestions-Discord-Bot#16]
```yml
{
    "commands": {
        "settings": {
            "set": {
                "suggestionChannel": {
                    "no_textchannel": "Kanál musí byť textový kanál (nie kanál noviniek)",
                    "success": "Kanál návrhov bol zmenený na {channel}."
                },
                "language": {
                    "select_language_option": "Vybrať {language} ako jazyk",
                    "success": "Jazyk bol úspešne zmenený na `{language}`.",
                    "select_language": "Vyberte jazyk, ktorý chcete použiť pre discord bota."
                },
                "authkey": {
                    "success": "Autorizačný token bol zmenený na `{token}`. Novú webovú adresu webhooku môžete nájsť pomocou príkazu `/webhookurl`."
                },
                "apikey": {
                    "invalid_key": "API URL alebo API KEY je neplatný.",
                    "success": "API key bol nastavený."
                }
            }
        },
        "suggest": {
            "modal-title": "Navrhni niečo!",
            "modal-question-1": "Názov návrhu",
            "modal-question-2": "Obsah návrhu",
            "success": "Tvoj návrh bol zaregistrovaný! Pozri si to tu: {link}",
            "cannot_find_user": "Potrebuješ mať prepojený Discord s webstránkou aby si mohol pridávať návrhy.",
            "validation-error": "Pri overovaní tvojho návrhu sa niečo pokazilo. Webová stránka vrátila nasledujúce hlásenie: {error}"
        
        },
        "webhookurl": {
            "generate_key_first": "Najprv musíte vygenerovať autorizačný token pomocou `/settings set authkey`.",
            "success": "Adresa URL je: `{url}`.\nPoužite túto webovú adresu ako webovú adresu discord webhooku pre modul návrhov."
        },
        "donate": "Ak chcete podporiť moju prácu a pokryť náklady na hosting, (mesačný) príspevok by som veľmi ocenil! Môžeš si vybrať jeden zo spôsobov [TU]({x})"
    },
    "permission_required": "Nemáte požadované povolenie \"{permission}\"",
    "suggestionHandler": {
        "suggestion": "Návrh",
        "suggestion_closed_website": "Návrh bol uzavretý na webovej stránke",
        "suggestion_opened_website": "Návrh bol otvorený na webovej stránke",
        "cannot_find_user": "Aby si mohol odpovedať cez discord, musíš mať prepojený svoj účet s webstránkou!",
        "suggested_by": "Navrhol {user}",
        "reaction_registered": "Tvoja reakcia `{reaction}` bola pridaná na webstránku."
    }
}
```

This is Slovak translation for this bot in newest version 1.1.0, added some components, which lacks in slovak translation 1.0.0.

Same in Webserver.js need to be 
```js
            const isNewSuggestion = !req.body.embeds
                ? req.body.event === 'newSuggestion'
                : (_c = req.body.embeds[0]) === null || _c === void 0 ? void 0 : _c.footer.text.includes('Nový návrh');
            const isNewComment = !req.body.embeds
                ? req.body.event === 'newSuggestionComment'
                : (_d = req.body.embeds[0]) === null || _d === void 0 ? void 0 : _d.footer.text.includes('Nový komentár');
```
instead of english one for proper working in Slovak Language
Better way will be to read these footer includes from language file, to better up the work with the bot for future users
